# Generated by Django 4.2.2 on 2023-06-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand_name', models.CharField(max_length=20)),
                ('genre', models.CharField(default='pls add genre', max_length=100)),
                ('developer', models.CharField(default='Please ADD Developer', max_length=30)),
                ('publisher', models.CharField(default='Please ADD Publisher', max_length=30)),
            ],
        ),
    ]
