# Generated by Django 4.2.2 on 2023-07-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand_name', models.CharField(max_length=20)),
                ('developer', models.CharField(default='', max_length=30)),
                ('publisher', models.CharField(default='', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('AXN', 'Action'), ('JRPG', 'JRPG'), ('FPS', 'First Person Shooter')], default='', max_length=6)),
            ],
        ),
    ]
