# Generated by Django 4.2.2 on 2023-06-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='developer',
            field=models.CharField(default='Please ADD Developer', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(default='pls add genre', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(default='Please ADD Publisher', max_length=30),
        ),
    ]
